import sys
tmpargv = sys.argv
sys.argv = []
import getopt
from array import array
import ROOT
from ROOT import gROOT, TFile, TTree, TChain, gDirectory, TLine, gStyle, TCanvas, TLegend, TH2F, TNtuple
sys.argv = tmpargv

#List arguments
def print_usage():
    print "\nUsage: {0} <output file base name> <input file name>".format(sys.argv[0])
    print "Arguments: "
    print '\t-h: this help message'
    print

options, remainder = getopt.gnu_getopt(sys.argv[1:], 'h')

# Parse the command line arguments
for opt, arg in options:
		if opt=='-h':
			print_usage()
			sys.exit(0)


outfile = remainder[0]
events = TChain("ntuple")
for i in range(1,len(remainder)):
    events.Add(remainder[i])


nevents = events.GetEntries()

BaduncVZ = array('d',[0])
BadbscChisq = array('d',[0])
BadtarChisq = array('d',[0])
eleBadTrkZ0 = array('d',[0])
posBadTrkZ0 = array('d',[0])
eleBadTrkD0 = array('d',[0])
posBadTrkD0 = array('d',[0])
eleBadLamdaKink1 = array('d',[0])
eleBadLamdaKink2 = array('d',[0])
eleBadLamdaKink3 = array('d',[0])
eleBadLamdaKink4 = array('d',[0])
eleBadLamdaKink5 = array('d',[0])
eleBadLamdaKink6 = array('d',[0])
posBadLamdaKink1 = array('d',[0])
posBadLamdaKink2 = array('d',[0])
posBadLamdaKink3 = array('d',[0])
posBadLamdaKink4 = array('d',[0])
posBadLamdaKink5 = array('d',[0])
posBadLamdaKink6 = array('d',[0])
eleBadPhiKink1 = array('d',[0])
eleBadPhiKink2 = array('d',[0])
eleBadPhiKink3 = array('d',[0])
eleBadPhiKink4 = array('d',[0])
eleBadPhiKink5 = array('d',[0])
eleBadPhiKink6 = array('d',[0])
posBadPhiKink1 = array('d',[0])
posBadPhiKink2 = array('d',[0])
posBadPhiKink3 = array('d',[0])
posBadPhiKink4 = array('d',[0])
posBadPhiKink5 = array('d',[0])
posBadPhiKink6 = array('d',[0])

TruthuncVZ = array('d',[0])
TruthbscChisq = array('d',[0])
TruthtarChisq = array('d',[0])
eleTruthTrkZ0 = array('d',[0])
posTruthTrkZ0 = array('d',[0])
eleTruthTrkD0 = array('d',[0])
posTruthTrkD0 = array('d',[0])
eleTruthLamdaKink1 = array('d',[0])
eleTruthLamdaKink2 = array('d',[0])
eleTruthLamdaKink3 = array('d',[0])
eleTruthLamdaKink4 = array('d',[0])
eleTruthLamdaKink5 = array('d',[0])
eleTruthLamdaKink6 = array('d',[0])
posTruthLamdaKink1 = array('d',[0])
posTruthLamdaKink2 = array('d',[0])
posTruthLamdaKink3 = array('d',[0])
posTruthLamdaKink4 = array('d',[0])
posTruthLamdaKink5 = array('d',[0])
posTruthLamdaKink6 = array('d',[0])
eleTruthPhiKink1 = array('d',[0])
eleTruthPhiKink2 = array('d',[0])
eleTruthPhiKink3 = array('d',[0])
eleTruthPhiKink4 = array('d',[0])
eleTruthPhiKink5 = array('d',[0])
eleTruthPhiKink6 = array('d',[0])
posTruthPhiKink1 = array('d',[0])
posTruthPhiKink2 = array('d',[0])
posTruthPhiKink3 = array('d',[0])
posTruthPhiKink4 = array('d',[0])
posTruthPhiKink5 = array('d',[0])
posTruthPhiKink6 = array('d',[0])


events.Branch("BaduncVZ",BaduncVZ,"BaduncVZ")
events.Branch("BadbscChisq",BadbscChisq,"BadbscChisq")
events.Branch("BadtarChisq",BadtarChisq,"BadtarChisq")
events.Branch("eleBadTrkZ0",eleBadTrkZ0,"eleBadTrkZ0")
events.Branch("posBadTrkZ0",posBadTrkZ0,"posBadTrkZ0")
events.Branch("eleBadTrkD0",eleBadTrkD0,"eleBadTrkD0")
events.Branch("posBadTrkD0",posBadTrkD0,"posBadTrkD0")
events.Branch("eleBadLamdaKink1",eleBadLamdaKink1,"eleBadLamdaKink1")
events.Branch("eleBadLamdaKink2",eleBadLamdaKink2,"eleBadLamdaKink2")
events.Branch("eleBadLamdaKink3",eleBadLamdaKink3,"eleBadLamdaKink3")
events.Branch("eleBadLamdaKink4",eleBadLamdaKink4,"eleBadLamdaKink4")
events.Branch("eleBadLamdaKink5",eleBadLamdaKink5,"eleBadLamdaKink5")
events.Branch("eleBadLamdaKink6",eleBadLamdaKink6,"eleBadLamdaKink6")
events.Branch("posBadLamdaKink1",posBadLamdaKink1,"posBadLamdaKink1")
events.Branch("posBadLamdaKink2",posBadLamdaKink2,"posBadLamdaKink2")
events.Branch("posBadLamdaKink3",posBadLamdaKink3,"posBadLamdaKink3")
events.Branch("posBadLamdaKink4",posBadLamdaKink4,"posBadLamdaKink4")
events.Branch("posBadLamdaKink5",posBadLamdaKink5,"posBadLamdaKink5")
events.Branch("posBadLamdaKink6",posBadLamdaKink6,"posBadLamdaKink6")
events.Branch("eleBadPhiKink1",eleBadPhiKink1,"eleBadPhiKink1")
events.Branch("eleBadPhiKink2",eleBadPhiKink2,"eleBadPhiKink2")
events.Branch("eleBadPhiKink3",eleBadPhiKink3,"eleBadPhiKink3")
events.Branch("eleBadPhiKink4",eleBadPhiKink4,"eleBadPhiKink4")
events.Branch("eleBadPhiKink5",eleBadPhiKink5,"eleBadPhiKink5")
events.Branch("eleBadPhiKink6",eleBadPhiKink6,"eleBadPhiKink6")
events.Branch("posBadPhiKink1",posBadPhiKink1,"posBadPhiKink1")
events.Branch("posBadPhiKink2",posBadPhiKink2,"posBadPhiKink2")
events.Branch("posBadPhiKink3",posBadPhiKink3,"posBadPhiKink3")
events.Branch("posBadPhiKink4",posBadPhiKink4,"posBadPhiKink4")
events.Branch("posBadPhiKink5",posBadPhiKink5,"posBadPhiKink5")
events.Branch("posBadPhiKink6",posBadPhiKink6,"posBadPhiKink6")

events.Branch("TruthuncVZ",TruthuncVZ,"TruthuncVZ")
events.Branch("TruthbscChisq",TruthbscChisq,"TruthbscChisq")
events.Branch("TruthtarChisq",TruthtarChisq,"TruthtarChisq")
events.Branch("eleTruthTrkZ0",eleTruthTrkZ0,"eleTruthTrkZ0")
events.Branch("posTruthTrkZ0",posTruthTrkZ0,"posTruthTrkZ0")
events.Branch("eleTruthTrkD0",eleTruthTrkD0,"eleTruthTrkD0")
events.Branch("posTruthTrkD0",posTruthTrkD0,"posTruthTrkD0")
events.Branch("eleTruthLamdaKink1",eleTruthLamdaKink1,"eleTruthLamdaKink1")
events.Branch("eleTruthLamdaKink2",eleTruthLamdaKink2,"eleTruthLamdaKink2")
events.Branch("eleTruthLamdaKink3",eleTruthLamdaKink3,"eleTruthLamdaKink3")
events.Branch("eleTruthLamdaKink4",eleTruthLamdaKink4,"eleTruthLamdaKink4")
events.Branch("eleTruthLamdaKink5",eleTruthLamdaKink5,"eleTruthLamdaKink5")
events.Branch("eleTruthLamdaKink6",eleTruthLamdaKink6,"eleTruthLamdaKink6")
events.Branch("posTruthLamdaKink1",posTruthLamdaKink1,"posTruthLamdaKink1")
events.Branch("posTruthLamdaKink2",posTruthLamdaKink2,"posTruthLamdaKink2")
events.Branch("posTruthLamdaKink3",posTruthLamdaKink3,"posTruthLamdaKink3")
events.Branch("posTruthLamdaKink4",posTruthLamdaKink4,"posTruthLamdaKink4")
events.Branch("posTruthLamdaKink5",posTruthLamdaKink5,"posTruthLamdaKink5")
events.Branch("posTruthLamdaKink6",posTruthLamdaKink6,"posTruthLamdaKink6")
events.Branch("eleTruthPhiKink1",eleTruthPhiKink1,"eleTruthPhiKink1")
events.Branch("eleTruthPhiKink2",eleTruthPhiKink2,"eleTruthPhiKink2")
events.Branch("eleTruthPhiKink3",eleTruthPhiKink3,"eleTruthPhiKink3")
events.Branch("eleTruthPhiKink4",eleTruthPhiKink4,"eleTruthPhiKink4")
events.Branch("eleTruthPhiKink5",eleTruthPhiKink5,"eleTruthPhiKink5")
events.Branch("eleTruthPhiKink6",eleTruthPhiKink6,"eleTruthPhiKink6")
events.Branch("posTruthPhiKink1",posTruthPhiKink1,"posTruthPhiKink1")
events.Branch("posTruthPhiKink2",posTruthPhiKink2,"posTruthPhiKink2")
events.Branch("posTruthPhiKink3",posTruthPhiKink3,"posTruthPhiKink3")
events.Branch("posTruthPhiKink4",posTruthPhiKink4,"posTruthPhiKink4")
events.Branch("posTruthPhiKink5",posTruthPhiKink5,"posTruthPhiKink5")
events.Branch("posTruthPhiKink6",posTruthPhiKink6,"posTruthPhiKink6")


truthtuple = TNtuple("truthtuple","truth tuple","uncVZ:bscChisq:tarChisq:eleTrkZ0:posTrkZ0:eleTrkD0:posTrkD0:eleLambdaKink1:eleLambdaKink2:eleLambdaKink3:eleLambdaKink4:eleLambdaKink5:eleLambdaKink6:posLambdaKink1:posLambdaKink2:posLambdaKink3:posLambdaKink4:posLambdaKink5:posLambdaKink6:elePhiKink1:elePhiKink2:elePhiKink3:elePhiKink4:elePhiKink5:elePhiKink6:posPhiKink1:posPhiKink2:posPhiKink3:posPhiKink4:posPhiKink5:posPhiKink6")
badtuple = TNtuple("badtuple","bad tuple","uncVZ:bscChisq:tarChisq:eleTrkZ0:posTrkZ0:eleTrkD0:posTrkD0:eleLambdaKink1:eleLambdaKink2:eleLambdaKink3:eleLambdaKink4:eleLambdaKink5:eleLambdaKink6:posLambdaKink1:posLambdaKink2:posLambdaKink3:posLambdaKink4:posLambdaKink5:posLambdaKink6:elePhiKink1:elePhiKink2:elePhiKink3:elePhiKink4:elePhiKink5:elePhiKink6:posPhiKink1:posPhiKink2:posPhiKink3:posPhiKink4:posPhiKink5:posPhiKink6")

#truthrootfile = TFile(outfile+"_truth.root","recreate")
badrootfile = TFile(outfile+"_bad.root","recreate")

for entry in xrange(nevents):
	events.GetEntry(entry)
	if(events.TruthtarChisq < -9998):
		continue

	truthVars = array('f')
	badVars = array('f')

	truthVars.append(events.TruthuncVZ)
	truthVars.append(events.TruthbscChisq)
	truthVars.append(events.TruthtarChisq)
	truthVars.append(events.eleTruthTrkZ0)
	truthVars.append(events.posTruthTrkZ0)
	truthVars.append(events.eleTruthTrkD0)
	truthVars.append(events.posTruthTrkD0)
	truthVars.append(events.eleTruthLambdaKink1)
	truthVars.append(events.eleTruthLambdaKink2)
	truthVars.append(events.eleTruthLambdaKink3)
	truthVars.append(events.eleTruthLambdaKink4)
	truthVars.append(events.eleTruthLambdaKink5)
	truthVars.append(events.eleTruthLambdaKink6)
	truthVars.append(events.posTruthLambdaKink1)
	truthVars.append(events.posTruthLambdaKink2)
	truthVars.append(events.posTruthLambdaKink3)
	truthVars.append(events.posTruthLambdaKink4)
	truthVars.append(events.posTruthLambdaKink5)
	truthVars.append(events.posTruthLambdaKink6)
	truthVars.append(events.eleTruthPhiKink1)
	truthVars.append(events.eleTruthPhiKink2)
	truthVars.append(events.eleTruthPhiKink3)
	truthVars.append(events.eleTruthPhiKink4)
	truthVars.append(events.eleTruthPhiKink5)
	truthVars.append(events.eleTruthPhiKink6)
	truthVars.append(events.posTruthPhiKink1)
	truthVars.append(events.posTruthPhiKink2)
	truthVars.append(events.posTruthPhiKink3)
	truthVars.append(events.posTruthPhiKink4)
	truthVars.append(events.posTruthPhiKink5)
	truthVars.append(events.posTruthPhiKink6)

	badVars.append(events.BaduncVZ)
	badVars.append(events.BadbscChisq)
	badVars.append(events.BadtarChisq)
	badVars.append(events.eleBadTrkZ0)
	badVars.append(events.posBadTrkZ0)
	badVars.append(events.eleBadTrkD0)
	badVars.append(events.posBadTrkD0)
	badVars.append(events.eleBadLambdaKink1)
	badVars.append(events.eleBadLambdaKink2)
	badVars.append(events.eleBadLambdaKink3)
	badVars.append(events.eleBadLambdaKink4)
	badVars.append(events.eleBadLambdaKink5)
	badVars.append(events.eleBadLambdaKink6)
	badVars.append(events.posBadLambdaKink1)
	badVars.append(events.posBadLambdaKink2)
	badVars.append(events.posBadLambdaKink3)
	badVars.append(events.posBadLambdaKink4)
	badVars.append(events.posBadLambdaKink5)
	badVars.append(events.posBadLambdaKink6)
	badVars.append(events.eleBadPhiKink1)
	badVars.append(events.eleBadPhiKink2)
	badVars.append(events.eleBadPhiKink3)
	badVars.append(events.eleBadPhiKink4)
	badVars.append(events.eleBadPhiKink5)
	badVars.append(events.eleBadPhiKink6)
	badVars.append(events.posBadPhiKink1)
	badVars.append(events.posBadPhiKink2)
	badVars.append(events.posBadPhiKink3)
	badVars.append(events.posBadPhiKink4)
	badVars.append(events.posBadPhiKink5)
	badVars.append(events.posBadPhiKink6)

	#truthtuple.Fill(truthVars)
	badtuple.Fill(badVars)
	del truthVars
	del badVars

#truthrootfile.cd()
#truthtuple.Write()
#truthrootfile.Close()

badrootfile.cd()
badtuple.Write()
badrootfile.Close()